strictness: veryhigh
doc-warnings: true
test-warnings: true

ignore-paths:
  - mission_control/static/
  - mission_control/migrations/
  - curriculum/migrations/
  - rovercode_web/users/
  - rovercode_web/contrib/
  - rovercode_web/blog/migrations/
  - config/
  - docs/
  - manage.py

pep8:
  full: true

pep257:
  run: true
  disable:
    # 1 blank line required before class docstring
    - D203
    # Multi-line docstring summary should start at the first line
    - D212

pylint:
  disable:
    - too-few-public-methods
    - invalid-name
    - too-many-ancestors
