version: '3'

volumes:
  postgres_data_dev: {}
  redis_data_dev: {}

services:
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      USE_DOCKER: 'yes'
      DEFAULT_ROVER_CONFIG: '{"left_eye_port": 1, "right_eye_port": 2, "left_motor_port": 3, "right_motor_port": 4}'
    volumes:
      - .:/app
    ports:
      - 8000:8000

  profanity-check:
    build:
      context: .
      dockerfile: ./compose/profanity/Dockerfile

  redis:
    image: redis:alpine
    volumes:
      - redis_data_dev:/data

  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOST=redis
    ports:
      - 8081:8081

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
