version: '3'

services:

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    env_file: .env

  redis:
    image: redis:alpine
